name: Docker Image CI

on:
  push:
    tags: 
      - '*'  # This will trigger the action on any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Get the Git tag
      id: get_tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag akhileshsre/navease-app:${{ env.TAG }}

    - name: Publish the Docker image
      run: docker push akhileshsre/navease-app:${{ env.TAG }}
