name: Docker Image CI

on:
  push:
    tags: 
      - '*'  # This will trigger the action on any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get the Git tag
      id: get_tag
      run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: akhileshsre/navease-app:${{ env.TAG }}
